### ISSUE TITLE
Update with HSM key generation support

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/credentials-support#19]
There has been an identified need to add functionalities to handle key generation inside an HSM slot for 2 major use cases

1. Generating keys and adding associated certificate to a HSM slot using script (not requiring a HSM using application to be present)
2. Generating and managing keys and associated certificate in a dedicated HSM slot from within the application using the HSM

Use-case 2 is primarily relevant for sign services where a user key is generated, used and destroyed without ever leaving the HSM.

In addition to this there is also a need for supporting scripts to automatically extract service keys from key stores and to load them into a SoftHSM token to test application usage with PKCS#11 for HSM support.

**Comment by martin-lindstrom** [comment]
Closed by PR https://github.com/swedenconnect/credentials-support/pull/20.
