### ISSUE TITLE
Support encrypted keys in configuration

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/credentials-support#48]
When using `PkiCredentialConfigurationProperties` to configure a `PkiCredential` it should be possible to supply a key password to unlock an encrypted key file.

**Comment by theseal** [comment]
Not sure if this is the correct place to mention it but support for Spring SSL Bundles would be nice and would probably solve the issue.
https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl

**Comment by martin-lindstrom** [comment]
Fixed in version 2.0.0
