### ISSUE TITLE
Update SoftHSM scripts to adapt to java 21 docker images

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/credentials-support#63]
Current latest Java version docker images do no longer support the "apt" command used in the Dockerfile-key-import.

This calls for a new strategy when building images for testing softhsm:

1. The actual docker image building the base image must use a more comprehensive base image that supports "apt" like "openjdk:21-jdk-buster". This means that softhsm should no longer be based an a common base image like "openjdk:21-jdk-slim".
2. As a separate base image must be build for Softhsm, this means that the softhsm and pkcs11tool components should be installed directly in the base image instead of as now, in Dockerfile-key-import.

A significant advantage of doing this is also that this speed up re-deployment and saves space in the docker registry as these tools are bing installed before the program is copied to the docker image. This means that you don't have to reinstall these tools in a new image every time you make a new release.

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/credentials-support/pull/64
